### PR TITLE
update /fem/setboundary.m

### PR DESCRIPTION
**Pull request by fangyuoy**
I annotated the judgment statement of dimension check. 
size(elem,2)>=4 will causes the two-dimensional quadrilateral element to be recognized as three-dimensional element, resulting in an error

### CODE REVIEW

**Review by scaomath — COMMENTED** [review]
The check should be still be there. You cannot just comment it out. You can modify the code to check both `node` dimension and `elem` dimension to check if it is a quadrilateral mesh.

**Comment by scaomath** [comment]
@fangyuoy Hello? Can you add an additional check on the `node` in the original code, if the second dim of `node` is 3 and that of `elem` is 4, then it must be tetrahedral elements. You basically want to exclude this case.

**Comment by fangyuoy** [comment]
@scaomath If the second dim of `node` is 2, it  must be a 2D problem. So we can only use size(node,2)>=3 to determine whether it's three-dimensional or not, if I'm not missing anything.

**Comment by scaomath** [comment]
Yes and no. `size(node,2)>=3` could be a simplicial 2d mesh on a 2D surface. The new modified code is still not good.
The original code works for all simplicial grids in 2d or surface mesh in 3d, could you please make this `if` condition works for the original cases?

**Comment by fangyuoy** [comment]
@scaomath `size(node,2)>=3 && size(elem,2)>=4` just excludes 2D quadrilateral elements compared to the original code `size(node,2)>=4`, this should be OK.

**Review by scaomath — COMMENTED** [review]
- A remark: right now it is impossible to exclude the case of 3D surface mesh with quadrilateral grid.

**Pull request merged**
